spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #本地测试localhost
    url: jdbc:mysql://localhost:3306/plh?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    #本地测试root 123456
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    max-wait: 5000
    initial-size: 2
    druid:
      connection-init-sqls: set names utf8mb4
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mp配置
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package:
  global-config:
    db-config:
      id-type: auto
    banner: false

#端口配置 本地测试8090 服务器8080
server:
  port: 8090
